/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./pages/count-down-circle/App.vue')['default']
    Circle: typeof import('./pages/count-down-circle/views/Circle.vue')['default']
    GetDetails: typeof import('./pages/loading/views/GetDetails.vue')['default']
    Huawei: typeof import('./pages/loading/views/Huawei.vue')['default']
    Index: typeof import('./pages/loading/views/Index.vue')['default']
    List: typeof import('./pages/loading/components/List.vue')['default']
    Loading: typeof import('./pages/loading/components/loading/Loading.vue')['default']
    Record: typeof import('./pages/loading/components/Record.vue')['default']
    Rongyao: typeof import('./pages/loading/views/Rongyao.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./pages/loading/components/Tab.vue')['default']
    Test: typeof import('./pages/loading/components/Test.vue')['default']
    UseDetails: typeof import('./pages/loading/views/UseDetails.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
